# version: '3.7'

# services:
#   sample:
#     container_name: sample
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - '.:/app'
#       - '/app/node_modules'
#     ports:
#       - 3001:3000
#     expose:
#       - 3001
#     environment:
#       - CHOKIDAR_USEPOLLING=true

version: '3.8'

services:
  dev:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '3000:3000'